### ISSUE TITLE
Update on packagist.org

### ISSUE THREAD

**Issue by truls1502** [pfrenssen/coder#12]
Thank you a lot for the release on https://www.drupal.org/project/coder/releases/8.x-3.0 - @pfrenssen 🎉 👍  

Do you mind to update on https://packagist.org/packages/drupal/coder too?

Let me know if you need an extra hand such as a co-maintainer, I am happy to help you.

**Comment by pfrenssen** [comment]
Thanks for the report, I have refreshed the version list on Packagist.

We could use some more help on the co-maintainer front probably. Would you be interested to start out by working on some PRs first?

**Comment by truls1502** [comment]
Yes of course, and sure that I would be happy to help you, @fenetikm and rest of your team with the created PRs and post new PR with the fixed bugs or new features that I can help and contribute to the module.

I have posted a new issue #13 :)

**Comment by pfrenssen** [comment]
Awesome, thanks!

**Comment by truls1502** [comment]
Hi @pfrenssen,

Finally back after seminars, conferences and board meeting in the last two weeks. 

However, could you update again on [packagist.org](https://packagist.org/packages/drupal/coder)? Because the version **8.3.1** is missing there 😄

**Comment by truls1502** [comment]
Tagging the active maintainers: @pfrenssen @fenetikm (sorry if I forget someone else)

Regarding the previous post, I can see someone has posted the same question on https://www.drupal.org/project/coder/issues/3001735 

In case you are quite busy at the moment, I can help you to update the issue on drupal.org once you have only released the newer version on Packagist website then after that, I can help you at drupal.org. 😄

**Comment by truls1502** [comment]
Adding @klausi too since I see he has access on packagist :)

**Comment by pfrenssen** [comment]
I manually updated the repo on Packagist.

I did a bit of research why this wasn't working any more, and I have re-authorized Packagist as was suggested in https://github.com/composer/packagist/issues/907. The status of the package looks fine now. Hopefully this will be updated automatically again in the future.
