### ISSUE TITLE
Update the default branch to 8.x-3.x on Drupal.org

### ISSUE THREAD

**Issue by truls1502** [pfrenssen/coder#13]
It seems 8.x-2.x is still the default branch. 

Since I do not have access, so it would be great if you can change the default branch at to **8.x-3.x** at https://www.drupal.org/node/105916/edit/default-branch if you have not done yet.

**Comment by pfrenssen** [comment]
I had actually already taken care of this but it takes some time for these changes to appear on the project page. I just checked and it all looks OK now. Thanks for the heads up!
