### ISSUE TITLE
Allow passing constants to t() translate function to prevent 'Only string literals should be passed to t() where possible' CS warning

### ISSUE THREAD

**Issue by MurzNN** [pfrenssen/coder#181]
It's a clone of the original issue in Drupal.org https://www.drupal.org/project/coder/issues/3326197

# Problem/Motivation

Now, when we try to pass a constant to the `t()` function, the code sniffer shows the warning:
`Only string literals should be passed to t() where possible`

But, as for me, using a constant is also ok, it's the same as a string literal.
Using constants is very convenient when we have several places to insert the same text: with constants, we can just put it once in a constant, and reuse it in all needed places, especially in different classes.

So, maybe we can find some way to allow this?

The current workaround to dismiss the warning is to use `// phpcs:ignore` or `@codingStandardsIgnoreStart` / `@codingStandardsIgnoreEnd` tricks around the `t()` call.

# Steps to reproduce

1. Get the code like this:
```php
define("ALIAS_RULES_DESCRIPTION", "Alias should start with /");
$description = $this->t(ALIAS_RULES_DESCRIPTION);
```

2. Run the code sniffer and see the warning.

# Proposed resolution

Try to detect if there is a constant passed, and if so - dismiss the warning.

I've found a way via allowing also T_STRING argument type, via this change:
```php
        if (
          $tokens[$argument['start']]['code'] !== T_CONSTANT_ENCAPSED_STRING
          && $tokens[$argument['start']]['code'] !== T_STRING
        ) {
```

It works well, and if I'm trying to pass a string with a inline variable like `"foo $bar"` - the argument type is `T_DOUBLE_QUOTED_STRING`, so it still works well for such case.

Could anyone check if this is a suitable fix, or it can also allow some "bad things" to pass?

**Comment by klausi** [comment]
Thanks, we don't use Github issues (only pull requests). Please continue the discussion in https://www.drupal.org/project/coder/issues/3326197
