### ISSUE TITLE
False Postive: Misshandled PHP 8.0 Attributes on Class properties leading to "Missing member variable doc comment"

### ISSUE THREAD

**Issue by WengerK** [pfrenssen/coder#213]
When having a class with PHP Attributes attached to properties we get the following phpcs error

> Missing member variable doc comment

```php
<?php

use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Foo class description.
 */
class Foo {

  /**
   * Bar property.
   *
   * @var bool
   */
  #[NotBlank]
  private bool $bar;

}
```

## Workaround 

A working workaround for now is to add the attribute before the comment, but it's not a very common practice on the Symfony landscape.

```php
<?php

use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Foo class description.
 */
class Foo {

  #[NotBlank]
  /**
   * Bar property.
   *
   * @var bool
   */
  private bool $bar;

}
```

PS: Opening another related issue about Aliased Attribute see #214

**Comment by jonathan1055** [comment]
Hi @WengerK
The issue queue here on github is not actually used for Coder issues. All discussions and issues are on the Drupal issue queue https://www.drupal.org/project/issues/coder 

I know this is not obvious, given the PRs are done here. But I suggest you raise an issue on d.o. then you should get some response. Same with your other issue #214 

Hope that helps.

**Comment by jonathan1055** [comment]
The project page does have a paragraph on contributing, but is it easily missed.

```
Contributing

1. Make sure an issue exists in the [issue queue](https://www.drupal.org/project/issues/coder)
2. Create a [Pull Request](https://help.github.com/articles/using-pull-requests/) against https://github.com/pfrenssen/coder
3. Post a link to the pull request to the issue on drupal.org and set the issue to "needs review"

```

**Comment by WengerK** [comment]
Posted on https://www.drupal.org/project/coder/issues/3408524 follow-up there.
