### ISSUE TITLE
Detection of DI on GlobalDrupalSniff is too loose.

### ISSUE THREAD

**Issue by b-sharpe** [pfrenssen/coder#238]
Currently the following must be true to catch `\Drupal::` calls in DI classes:

1. Class doesn't extend anything OR Doesn't extend one of those defined as base classes
2. Is not a service itself
3. Doesn't implement `ContainerInjectionInterface`

So this omits a lot of legit cases of plugins as they commonly will use `ContainerFactoryPluginInterface`

**Comment by klausi** [comment]
Issues are done at https://www.drupal.org/project/issues/coder , please search or create one there!
