### ISSUE TITLE
Drupal.Classes.FullyQualifiedNamespace: multi-use statements false positive

### ISSUE THREAD

**Issue by jrfnl** [pfrenssen/coder#80]
Multi-use statements are not supported:
```php
use Vendor\Foo\ClassA as ClassABC,
    Vendor\Bar\InterfaceB,
    Vendor\Baz\ClassC;
```

Throws:
```
  7 | ERROR | [x] Namespaced classes/interfaces/traits should be referenced with use statements
    |       |     (Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing)
  8 | ERROR | [x] Namespaced classes/interfaces/traits should be referenced with use statements
    |       |     (Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing)
```

**Comment by arkener** [comment]
[PSR-2](https://www.php-fig.org/psr/psr-2/#3-namespace-and-use-declarations), which is currently used by this project to check the usage of use declarations defines that 

> There MUST be one use keyword per declaration.

Currently you should also receive the following error:
` 6 | ERROR | [x] There must be one USE keyword per declaration (PSR2.Namespaces.UseDeclaration.MultipleDeclarations)`

**Comment by jrfnl** [comment]
@Arkener Sniffs should function independently of another and not hide one error behind another, so my bug report is perfectly valid.

**Comment by arkener** [comment]
@jrfnl I apologize, I didn't mean your bug report isn't valid, I'm just noting why you might be receiving the error given by this project, as the given error might be the result of a cascading sniff message.

**Comment by klausi** [comment]
Thanks for the report! Please file issues at https://www.drupal.org/project/issues/coder in the future so that we can give you contribution credit on drupal.org :-)

@jrfnl please comment there if you want to receive credit.

Moving this to https://www.drupal.org/project/coder/issues/3118337
